sonar.host.url=http://localhost:9000/
sonar.token=sqp_8d36c9465a63bdb96f6b5fcee0de7a80c6dbff13
sonar.projectKey=nestjs-test
sonar.projectName=nestjs-test
sonar.projectVersion=1.0
sonar.projectDescription=Description for "My App" project...
sonar.sources=.
sonar.inclusions=src/**/*.ts
sonar.coverage.exclusions=node_modules/*,package.json,.scannerwork,.env,public/*,protos/*,test/*
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.spec.tsx,src/**/*.test.ts,src/**/*.test.tsx