name: Workflow Dev

on:
  workflow_dispatch:
  push:
    branches:
      - "dev"

jobs:
  call_ci_process:
    name: Run CI Process
    uses: lamquangmanh/github-workflows/.github/workflows/ci.yml@main
    with:
      environment: dev
    secrets: inherit

  call_cd_process:
    name: Run Artifact Registry Process
    uses: lamquangmanh/github-workflows/.github/workflows/cd.yml@main
    with:
      environment: dev
      repository_path: "quangmanhlam/user-bff-dev"
    secrets: inherit

  call_k8s_process:
    name: Run K8s Process
    needs: call_cd_process
    uses: lamquangmanh/github-workflows/.github/workflows/k8s.yml@main
    with:
      environment: dev
      gitops_path: "microk8s/microservice/apps/user-bff/overlays/dev"
      repository_path: "quangmanhlam/user-bff-dev"
    secrets: inherit
